debug: true

logging:
  level:
    org.springframework.boot.context.web.OrderedRequestContextFilter: INFO

browse:
  enabled: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: .ssl/keystore
    key-store-password: password
    key-alias: scribbler
    trust-store: .ssl/truststore
    trust-store-password: password
