spring:
  resources:
    static-locations: file:repository/public/

browse:
  enabled: false

repository:
  content-store: repository/content
  public-content: repository/public
  include-header: repository/include/header.html
  include-footer: repository/include/footer.html
